// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkA9xWzQsNQBTFz8MUsFqhxpNl0T_qvo',
    appId: '1:824462971159:web:bac2e71696b6f36342a752',
    messagingSenderId: '824462971159',
    projectId: 'prestadoraki',
    authDomain: 'prestadoraki.firebaseapp.com',
    storageBucket: 'prestadoraki.firebasestorage.app',
    measurementId: 'G-H3FD05QZGE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAnG8dOAFJp9NopI56X9X2eDAuFdDMEhk',
    appId: '1:824462971159:ios:4eb933a022860a7342a752',
    messagingSenderId: '824462971159',
    projectId: 'prestadoraki',
    storageBucket: 'prestadoraki.firebasestorage.app',
    iosBundleId: 'com.opoutsourcing.prestadoraki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkA9xWzQsNQBTFz8MUsFqhxpNl0T_qvo',
    appId: '1:824462971159:web:994379f67a633dca42a752',
    messagingSenderId: '824462971159',
    projectId: 'prestadoraki',
    authDomain: 'prestadoraki.firebaseapp.com',
    storageBucket: 'prestadoraki.firebasestorage.app',
    measurementId: 'G-QDPS6NLX6M',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAnG8dOAFJp9NopI56X9X2eDAuFdDMEhk',
    appId: '1:824462971159:ios:4eb933a022860a7342a752',
    messagingSenderId: '824462971159',
    projectId: 'prestadoraki',
    storageBucket: 'prestadoraki.firebasestorage.app',
    iosBundleId: 'com.opoutsourcing.prestadoraki',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBCDxXqpfivHNfT8bVKpNTMHw_sJHnIWc',
    appId: '1:824462971159:android:c218dcabfc0c018842a752',
    messagingSenderId: '824462971159',
    projectId: 'prestadoraki',
    storageBucket: 'prestadoraki.firebasestorage.app',
  );
}
